#FRONTEND 
name: Build React Files & Deploy to Ubuntu server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
        #cache: 'npm'
    - run: npm install
    - run: REACT_APP_STAGE=production
    - run: CI=false npm run build
    - name: ssh deploy on server
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ibis/test-deployment
            git pull origin master
            npm install
            npm run build
            pm2 restart 2
