name: remote ssh command
on:
  push:
    branches: [master]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v2
         - name: Use Node.js 20.x to Build
           uses: actions/setup-node@v2
      with:
        node-version: 20.x
        -name: ssh deploy on Server
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ibis/test-deployment
            git pull master
            npm install
            npm run build
            pm2 restart 2
